import assert from 'node:assert/strict';
import {calculateDamage,build} from '../engine/calculate-damage.mjs';
import {cardCasterKeys,cardPropertyKeys,playerSetupKeys} from '../engine/card-offensive-setup.mjs';
import {targetKeys} from '../engine/active-target.mjs';
const zero=keys=>Object.fromEntries(keys.map(k=>[k,0]));
const setup={build,value:100,caster:zero(cardCasterKeys),player:{...zero(playerSetupKeys),damage_plus:50},card:{...zero(cardPropertyKeys),card_damage_plus:10},tags:['Card_Strike'],instructionCard:true,stateTriggerAdd:false,dimensionFixPer:0,skillArgsPlus:0};
const target={...zero(targetKeys),isCrit:true,awakerCritDamage:150,enemyStateDmgMultiplier:1};
const hit={immune:false,block:75,puncture:false,hp:200,retainHp:80,limit:100,usedLimit:20,deathResist:0,preventEligible:true};
const input={mode:'experimental',build,damageType:'ACTIVE',offenseSetup:setup,target,hitResolution:hit};
const inputSnapshot=JSON.stringify(input);
const out=calculateDamage(input),request=out.experimentalModels[1];
assert.equal(JSON.stringify(input),inputSnapshot);
assert.equal(out.offensiveUtility.showDamage,160);
assert.equal(request.incomingDamage,400);
assert.deepEqual(request.shield,[325,75,75,true,false,0]);
assert.equal(request.afterRetain,120);assert.equal(request.converted,205);assert.equal(request.hpLossRequest,80);
assert.equal(out.finalDamage,null);assert.equal(out.status,'EXPERIMENTAL');
const hpModel=out.experimentalModels[2];
assert.equal(hpModel.incomingDamage,400);assert.equal(hpModel.hpLossRequest,80);
assert.equal(hpModel.modeledHpLost,80);assert.equal(hpModel.hpAfter,120);assert.equal(hpModel.overflowDiagnostic,null);
assert.equal(hpModel.callbackDescriptors[0].new,120);
assert.ok(out.unresolvedDependencies.some(s=>s.includes('callbacks')));
const strict=calculateDamage({...input,mode:'strict'});assert.equal(strict.finalDamage,null);assert.deepEqual(strict.experimentalModels,[]);
const immune=calculateDamage({...input,hitResolution:{...hit,immune:true,preventEligible:false}}).experimentalModels[1];
assert.equal(immune.incomingDamage,400);assert.equal(immune.hpLossRequest,0);assert.equal(immune.shield[5],75);
const immuneHp=calculateDamage({...input,hitResolution:{...hit,immune:true,preventEligible:false}}).experimentalModels[2];
assert.equal(immuneHp.modeledHpLost,0);assert.equal(immuneHp.hpAfter,200);assert.equal(immuneHp.shieldAfter,75);
const overkillInput={...input,hitResolution:{...hit,block:0,hp:5,retainHp:0,limit:0,usedLimit:0,preventEligible:false}};
const overkill=calculateDamage(overkillInput).experimentalModels[2];
assert.equal(overkill.incomingDamage,400);assert.equal(overkill.hpLossRequest,400);assert.equal(overkill.modeledHpLost,5);assert.equal(overkill.hpAfter,0);assert.equal(overkill.overflowDiagnostic,395);
const resisted=calculateDamage({...overkillInput,hitResolution:{...overkillInput.hitResolution,deathResist:1}}).experimentalModels[2];
assert.equal(resisted.hpLossRequest,4);assert.equal(resisted.modeledHpLost,4);assert.equal(resisted.hpAfter,1);
const fractional=calculateDamage({...overkillInput,hitResolution:{...overkillInput.hitResolution,hp:.5}}).experimentalModels[2];
assert.equal(fractional.modeledHpLost,.5);assert.equal(fractional.hpAfter,0);
assert.throws(()=>calculateDamage({...input,offense:{}}),/exactly one/);
assert.throws(()=>calculateDamage({...input,offenseSetup:{...setup,build:'other'}}),/match/);
assert.throws(()=>calculateDamage({...input,hitResolution:{...hit,immune:true}}),/Immune/);
assert.throws(()=>calculateDamage({...input,hitResolution:{...hit,damage:1}}),/Explicit/);

// An ordinary fractional Arg rounds before card scaling. A card override does not.
const {value:unusedValue,...snapshotSetup}=setup;
snapshotSetup.card={...setup.card,card_damage_per:100};
const snapshotInput={...input,offenseSetup:snapshotSetup,skillArgumentSnapshot:{raw:[49.5],overrides:[],argumentIndex:1}};
const rounded=calculateDamage(snapshotInput);
assert.equal(rounded.skillArgumentSnapshot.value,50);
assert.equal(rounded.offensiveUtility.showDamage,160);
assert.equal(rounded.experimentalModels[0].preHitDamage,400);
assert.ok(rounded.evidence.includes('PC144:SkillArgumentNormalization'));
const overridden=calculateDamage({...snapshotInput,skillArgumentSnapshot:{raw:[49.5],overrides:[49.5],argumentIndex:1}});
assert.equal(overridden.skillArgumentSnapshot.value,49.5);
assert.equal(overridden.offensiveUtility.showDamage,159);
const zeroOverride=calculateDamage({...snapshotInput,skillArgumentSnapshot:{raw:[49.5],overrides:[0],argumentIndex:1}});
assert.equal(zeroOverride.skillArgumentSnapshot.value,0);
assert.equal(zeroOverride.offensiveUtility.showDamage,60);
assert.throws(()=>calculateDamage({...snapshotInput,offenseSetup:setup}),/without value/);
assert.throws(()=>calculateDamage({...snapshotInput,skillArgumentSnapshot:{raw:[1],overrides:[],argumentIndex:0}}),/one-based/);
assert.throws(()=>calculateDamage({...snapshotInput,skillArgumentSnapshot:{raw:[1],overrides:[],argumentIndex:2}}),/one-based/);
assert.equal(calculateDamage({...snapshotInput,mode:'strict'}).finalDamage,null);
assert.deepEqual(calculateDamage({...snapshotInput,mode:'strict'}).experimentalModels,[]);
