import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {webcrypto} from 'node:crypto';
import {loadVerifiedRuntime} from '../website/dist/verified-runtime.mjs';
import {verifyRuntimeManifest} from '../tools/verify_runtime_manifest.mjs';
const fetchFile=async path=>({ok:true,arrayBuffer:async()=>readFileSync(new URL('../website/dist/'+path,import.meta.url))});
const options={fetchFile,digest:bytes=>webcrypto.subtle.digest('SHA-256',bytes),makeUrl:source=>'data:text/javascript;base64,'+Buffer.from(source).toString('base64'),revokeUrl:()=>{}};
test('browser loader executes checked module bytes with the CLI runtime fingerprint',async()=>{
  const runtime=await loadVerifiedRuntime(options);assert.equal(runtime.runtimeFingerprint,verifyRuntimeManifest());
  const directInput=JSON.parse(readFileSync(new URL('../research/examples/theorycraft-installed-direct-tentacle-command.json',import.meta.url))).input;
  assert.equal(runtime.calculateDirectTentacleCommand(directInput).preHitDamage,235);
  const build='pc-res144-build51',timeline={schemaVersion:1,build,interveningEffects:'assumed-absent',target:{hp:1000,block:0},steps:[{id:'one',immune:false,puncture:false,scenario:{build,mode:'experimental',damageType:'PURE',effect:{build,category:'PURE',targetDead:false,baseDamage:10}}}]};
  assert.equal(runtime.runResearchTimeline(timeline).modeledHpLost,10);
  const snapshot={schemaVersion:2,kind:'morimens-battle-property-snapshot-damage',build:'pc-res150-build51',snapshotStage:'battle-property-server-live',snapshotCompleteness:'complete-map',baseValue:100,skillArgsPlus:0,tags:['Card_Strike'],casterProperties:{crit:100,crit_damage:50,crit_damage_from_strikecard:10,crit_damage_per:0,damage_per2monster_boss:20},playerProperties:{dimension_fix_per:0},targetProperties:{hp:1000,max_hp:1000,block:50,be_damage_per:10,vulnerable_per:50},cardProperties:{},cardContext:{present:false,instructionCard:false,stateTriggerAdd:false},targetContext:{critRoll:null,targetBattleTag:'Boss',targetStateIds:[]},hitContext:{damageSubtype:'Ordinary'}};
  const snapshotResult=runtime.calculateSnapshotActiveDamage(snapshot);assert.equal(snapshotResult.preHitDamage,317);assert.equal(snapshotResult.modeledHpLost,267);
  const sequence={schemaVersion:1,kind:'morimens-snapshot-active-sequence',build:'pc-res150-build51',snapshotStage:'battle-property-server-live',snapshotCompleteness:'complete-map',interveningEffects:'assumed-absent',casterProperties:snapshot.casterProperties,playerProperties:snapshot.playerProperties,initialTargetProperties:snapshot.targetProperties,hits:[{id:'one',baseValue:100,skillArgsPlus:0,tags:snapshot.tags,cardProperties:{},cardContext:snapshot.cardContext,targetContext:snapshot.targetContext,hitContext:snapshot.hitContext},{id:'two',baseValue:100,skillArgsPlus:0,tags:snapshot.tags,cardProperties:{},cardContext:snapshot.cardContext,targetContext:snapshot.targetContext,hitContext:snapshot.hitContext}]};
  assert.equal(runtime.runSnapshotActiveSequence(sequence).executedHits,2);
  const actions=runtime.syntheticCardActionExample();
  assert.equal(runtime.runCardActionTimeline(actions).modeledHpLost,500);
  actions.steps.reverse();assert.equal(runtime.runCardActionTimeline(actions).completed,false);
  const mixed=runtime.runDamageEnergyCommand(runtime.syntheticDamageEnergyExample());
  assert.equal(mixed.modeledHpLost,120);assert.equal(mixed.casterEnergyAfter,100);
  const wheel=runtime.advanceDoomsdayAfterUseCard({schemaVersion:1,kind:'morimens-after-use-card-wheel-trigger',build:'pc-res144-build51',wheelId:'wheel-0029',refinementLevel:3,cardType:'Card_Strike',ownerAttack:1000,counter:0,strikecardDamagePlus:0});
  assert.equal(wheel.transition.strikecardDamagePlusAfter,250);assert.equal(wheel.finalDamage,null);
  const wheelSequence=runtime.runWheelEventSequence({schemaVersion:1,kind:'morimens-wheel-event-sequence',build:'pc-res144-build51',initialState:{doomsday:{refinementLevel:3,ownerAttack:1000,counter:0,baseStrikecardDamagePlus:0,wheelStrikecardDamagePlus:0},light:null,arachne:null},steps:[{id:'one',type:'AFTER_USE_CARD',cardType:'Card_Strike'},{id:'end',type:'AFTER_BOUT_END'}]});
  assert.equal(wheelSequence.trace[0].after.doomsday.strikecardDamagePlus,250);assert.equal(wheelSequence.finalState.doomsday.strikecardDamagePlus,0);
  const wheelHit=id=>({id,type:'ACTIVE_HIT',baseValue:100,skillArgsPlus:0,tags:['Card_Strike'],cardProperties:{},cardContext:{present:false,instructionCard:false,stateTriggerAdd:false},targetContext:{critRoll:null,targetBattleTag:'Boss',targetStateIds:[]},hitContext:{damageSubtype:'Ordinary'}});
  const wheelActive=runtime.runWheelActiveTimeline({schemaVersion:1,kind:'morimens-wheel-active-timeline',build:'pc-res144-build51',snapshotStage:'battle-property-server-live',snapshotCompleteness:'complete-map',initialWheelState:{doomsday:{refinementLevel:3,ownerAttack:1000,counter:0,baseStrikecardDamagePlus:0,wheelStrikecardDamagePlus:0},light:null,arachne:null},baseCasterProperties:{crit:0,crit_damage:0,crit_damage_from_strikecard:0,crit_damage_per:0,strikecard_damage_plus:0},basePlayerProperties:{dimension_fix_per:0},initialTargetProperties:{hp:1000,max_hp:1000,block:0,be_damage_per:0,vulnerable_per:0},steps:[wheelHit('first'),{id:'after-first',type:'AFTER_USE_CARD',cardType:'Card_Strike'},wheelHit('second')]});
  assert.equal(wheelActive.modeledHpLost,450);assert.equal(wheelActive.trace[2].result.preHitDamage,350);
  const reordered=JSON.parse(JSON.stringify(wheelActive.trace.length&&{schemaVersion:1,kind:'morimens-wheel-active-timeline',build:'pc-res144-build51',snapshotStage:'battle-property-server-live',snapshotCompleteness:'complete-map',initialWheelState:{doomsday:{refinementLevel:3,ownerAttack:1000,counter:0,baseStrikecardDamagePlus:0,wheelStrikecardDamagePlus:0},light:null,arachne:null},baseCasterProperties:{crit:0,crit_damage:0,crit_damage_from_strikecard:0,crit_damage_per:0,strikecard_damage_plus:0},basePlayerProperties:{dimension_fix_per:0},initialTargetProperties:{hp:1000,max_hp:1000,block:0,be_damage_per:0,vulnerable_per:0},steps:[wheelHit('first'),wheelHit('second'),{id:'after-first',type:'AFTER_USE_CARD',cardType:'Card_Strike'}]}));
  const original={...reordered,steps:[reordered.steps[0],reordered.steps[2],reordered.steps[1]]};const compared=runtime.compareWheelActiveTimelines({schemaVersion:1,kind:'morimens-wheel-active-comparison',baseline:original,candidate:reordered},{runtimeFingerprint:runtime.runtimeFingerprint});
  assert.equal(compared.reproducibility,'RUNTIME_PINNED');assert.equal(compared.orderOnly,true);assert.equal(compared.modeledHpLostDelta,-250);
  const paidConditions={cardExists:true,inHand:true,judgeCost:true,commandExists:true,dead:false,strike:true,allowIgnoreCost:false,cardUseless:0,ownerUseless:0,coma:0,comaImmunity:0,ownerForbid:0,playerForbid:0,ownerForbidStrike:0,playerForbidStrike:0};const paidAction=(id,cost)=>({id,cardInstanceId:`card-${id}`,cardType:'Card_Strike',costInput:{cfgCost:String(cost),originCost:cost,delta:0,harmonize:0,fixedSwitches:{},keeper:false,keeperCost:null,pvp:false},conditions:paidConditions,effects:[wheelHit(`${id}:hit`)]});
  const paid=runtime.runPaidWheelActiveTimeline({schemaVersion:1,kind:'morimens-paid-wheel-active-timeline',build:'pc-res144-build51',initialEnergy:4,snapshotStage:'battle-property-server-live',snapshotCompleteness:'complete-map',initialWheelState:original.initialWheelState,baseCasterProperties:original.baseCasterProperties,basePlayerProperties:original.basePlayerProperties,initialTargetProperties:original.initialTargetProperties,actions:[paidAction('one',2),paidAction('two',2)]});assert.equal(paid.acceptedActions,2);assert.equal(paid.modeledHpLost,450);assert.equal(paid.finalWheelState.doomsday.strikecardDamagePlus,500);
  const paidTimeline={schemaVersion:1,kind:'morimens-paid-wheel-active-timeline',build:'pc-res144-build51',initialEnergy:4,snapshotStage:'battle-property-server-live',snapshotCompleteness:'complete-map',initialWheelState:original.initialWheelState,baseCasterProperties:original.baseCasterProperties,basePlayerProperties:original.basePlayerProperties,initialTargetProperties:original.initialTargetProperties,actions:[paidAction('one',2),paidAction('two',2)]};const paidSearch=runtime.searchPaidWheelOrders({schemaVersion:1,kind:'morimens-paid-wheel-order-search',objective:'MAX_MODELED_HP_LOST',timeline:paidTimeline,maxEvaluations:10,returnTop:2});assert.equal(paidSearch.evaluatedPermutations,2);assert.equal(paidSearch.best.modeledHpLost,450);
  const multiCaster=JSON.parse(readFileSync(new URL('../research/examples/theorycraft-multi-caster-wheel-active-timeline.json',import.meta.url))).input,multiResult=runtime.runWheelActiveTimeline(multiCaster);assert.equal(multiResult.modeledHpLost,595);assert.deepEqual(multiResult.trace.filter(row=>row.type==='ACTIVE_HIT').map(row=>row.result.preHitDamage),[110,485]);
  const states=runtime.syntheticStateSequenceExample();
  assert.equal(runtime.runStateSequenceExperiment(states).modeledHpLost,520);
  [states.steps[0],states.steps[1]]=[states.steps[1],states.steps[0]];
  assert.equal(runtime.runStateSequenceExperiment(states).modeledHpLost,550);
  const queried=runtime.syntheticStateSequenceExample();
  queried.stateQueries={'CmdCaster.GetStateLayer':{liveOwner:'actor'}};
  queried.definitions=[{id:90001,owner:'actor',maximum:'10',properties:[],skillLevel:1,caster:1,specialValue:0,banned:false}];
  queried.steps=[{type:'addState',definitionId:90001,resolvedLayers:2},{type:'attack',rows:[{id:'state-hit',Type:'BEActiveDamage',Target:'UpperTarget',Para:'100+CmdCaster.GetStateLayer(90001)*10',Cond:'CmdCaster.GetStateLayer(90001)>0'}]}];
  assert.equal(runtime.runStateSequenceExperiment(queried).modeledHpLost,120);
  queried.steps.push({type:'removeState',definitionId:90001},queried.steps[1]);
  const removed=runtime.runStateSequenceExperiment(queried);assert.equal(removed.modeledHpLost,120);assert.equal(removed.trace[3].result.hits.length,0);
  const saved=runtime.compareTimelines({schemaVersion:1,kind:'morimens-timeline-comparison',baseline:timeline,candidate:timeline},{runtimeFingerprint:runtime.runtimeFingerprint});
  assert.equal(saved.reproducibility,'RUNTIME_PINNED');assert.equal(saved.modeledHpLostDelta,0);
});
test('changed bytes fail verification before any engine import',async()=>{
  let imported=false;
  await assert.rejects(()=>loadVerifiedRuntime({...options,fetchFile:async path=>path==='engine/research-timeline.mjs'?{ok:true,arrayBuffer:async()=>new TextEncoder().encode('changed')}:fetchFile(path),importModule:async()=>{imported=true;return {};}}),/Runtime asset changed/);
  assert.equal(imported,false);
});
