import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolveClientAdvancementPrimary} from '../engine/client-build-stats.mjs';

const data=JSON.parse(readFileSync(new URL('../research/evidence/client-build-data.json',import.meta.url),'utf8'));
const report=JSON.parse(readFileSync(new URL('../research/evidence/mouchette-case-study-primary.json',import.meta.url),'utf8'));

test('Mouchette case-study primary inputs are generated by the general client resolver',()=>{
  for(const row of Object.values(report.characters)){
    const p=row.progression,result=resolveClientAdvancementPrimary({build:row.build,characterId:row.characterId,level:p.level,gnosticRank:p.gnosticRank,advancementTalentId:p.advancementTalentId,advancementLevel:p.advancementLevel},data);
    assert.deepEqual(row.stats,result.stats);assert.deepEqual(row.baseStats,result.baseStats);assert.deepEqual(row.trace,result.trace);
  }
  assert.equal(report.characters.mouchette.stats.ATK,258);
  assert.equal(report.characters.arachne.stats.ATK,138);
  assert.equal(report.finalDamage,null);
});
