import assert from 'node:assert/strict';
import {resolvePhaseHpLoss,simulatePhaseCapHits} from '../engine/phase-cap.mjs';
const phase={maxHp:1000,phaseId:60409,phaseLayers:331,counter:0,immune:false};
const result=simulatePhaseCapHits({hp:1000,block:0,phase,hits:[200,200,200]});
assert.deepEqual(result.trace.map(h=>h.hpLost),[200,130,0]);
assert.equal(result.trace[0].after.phase.counter,200);
assert.equal(result.trace[1].before.phase.counter,200);
assert.deepEqual(result.ending,{hp:670,block:0,phase:{...phase,phaseId:60408,immune:true}});
assert.ok(result.evidence.includes('PC144:PhaseCapExpressions'));
assert.ok(result.evidence.includes('PC144:PhaseTransitionEffects'));
assert.equal(result.finalDamage,null);
const shield=simulatePhaseCapHits({hp:1000,block:75,phase,hits:[200,400,100]});
assert.deepEqual(shield.trace.map(h=>h.hpLost),[125,205,0]);
assert.equal(shield.trace[0].after.phase.counter,125);
assert.equal(shield.trace[0].shieldLoss,75);
const phase2=resolvePhaseHpLoss({...phase,phaseId:60408},330);
assert.deepEqual(phase2.operations.map(o=>o.type),['addCounter','subtractPhase','addState','changeMonsterSkill','removeState','removeState']);
assert.equal(phase2.operations[3].skillId,60398);
assert.equal(phase2.operations[3].changeType,1);
assert.equal(phase2.state.phaseId,0);assert.equal(phase2.state.counter,0);assert.equal(phase2.state.immune,true);
assert.deepEqual(resolvePhaseHpLoss(phase,0),{state:phase,operations:[]});
assert.throws(()=>resolvePhaseHpLoss(phase,.5),/integer/);
assert.throws(()=>simulatePhaseCapHits({hp:1000,block:0,phase,hits:[,200]}),/Dense/);
