import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';

test('decoded replay index preserves initialization and chronological evidence events',()=>{
  const code=`import json\nfrom tools.replay_index import build_replay_index\nc=json.load(open('research/evidence/replay-protocol.json',encoding='utf-8'))\na={'schemaVersion':1,'kind':'MORIMENS_DECODED_REPLAY','inputSha256':'abc','decoded':{'battleDat':{'stageId':9},'unZippedRecord':[{'time':0,'msgId':c['commands']['rd_InitBattle'],'msgData':{'battleUuid':'u','roleDataList':[{'uid':1,'properties':{'crit':100}}],'monsterDataList':[{'uid':2,'properties':{'hp':999,'block':20}}],'cardDataList':[{'uid':3}]}},{'time':1,'msgId':c['commands']['rd_BattleCut'],'msgData':{'frameList':[{'time':1.1,'eventId':c['renderEvents']['UseCard'],'data':{'cardUid':3,'camp':1}}]}},{'time':1.15,'msgId':c['commands']['rd_CommandResult'],'msgData':{'msgId':c['commands']['lg_SelectTargets'],'uids':[2]}},{'time':1.2,'msgId':c['commands']['rd_BattleCut'],'msgData':{'frameList':[{'time':1.2,'eventId':c['renderEvents']['PropertyChanged'],'data':{'uid':2,'propertyType':'block','value':0,'changedValue':-20}},{'time':1.25,'eventId':c['renderEvents']['PropertyChanged'],'data':{'uid':2,'propertyType':'hp','value':900,'changedValue':-99}},{'time':1.3,'eventId':c['renderEvents']['AddState'],'data':{'ownerUid':2,'stateUid':10,'stateId':2934,'layer':1}},{'time':1.4,'eventId':c['renderEvents']['BeHit'],'data':{'roleUid':2,'beHitConfig':{'oldHp':999,'blockLose':20,'castDamage':119}}}]}}]}}\nprint(json.dumps(build_replay_index(a,c),separators=(',',':')))\n`;
  const run=spawnSync('python',['-c',code],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const result=JSON.parse(run.stdout);
  assert.equal(result.initializations[0].roleDataList[0].properties.crit,100);assert.equal(result.events.length,5);assert.equal(result.cardUses[0].data.cardUid,3);assert.equal(result.propertyChanges[1].data.value,900);assert.equal(result.stateEvents[0].eventName,'AddState');assert.equal(result.hits[0].data.beHitConfig.castDamage,119);assert.deepEqual(result.unknownEvents,[]);
  assert.equal(result.snapshotBoundaryStatus,'COMPLETE');assert.equal(result.actionSnapshots.length,1);assert.equal(result.actionSnapshots[0].boundaryStatus,'COMPLETE');assert.equal(result.actionSnapshots[0].roles['2'].properties.hp,999);assert.equal(result.actionSnapshots[0].cards['3'].uid,3);assert.deepEqual(result.actionSnapshots[0].activeStates,[]);
  assert.deepEqual(result.actionSnapshots[0].window.selectedTargetCommands[0].data.uids,[2]);assert.equal(result.actionSnapshots[0].window.hits.length,1);assert.equal(result.commandResults[0].commandName,'lg_SelectTargets');
  assert.equal(result.hitSnapshots.length,1);assert.equal(result.hitSnapshots[0].boundaryStatus,'COMPLETE');assert.equal(result.hitSnapshots[0].roles['2'].properties.hp,999);assert.equal(result.hitSnapshots[0].roles['2'].properties.block,20);assert.equal(result.hitSnapshots[0].activeStates[0].stateId,2934);assert.equal(result.actionSnapshots[0].window.hitSnapshots[0].hitIndex,0);
});

test('decoded replay index preserves nonobject presentation event data',()=>{
  const code=`import json\nfrom tools.replay_index import build_replay_index\nc=json.load(open('research/evidence/replay-protocol.json',encoding='utf-8'))\na={'schemaVersion':1,'kind':'MORIMENS_DECODED_REPLAY','inputSha256':'abc','decoded':{'battleDat':{},'unZippedRecord':[{'time':0,'msgId':c['commands']['rd_InitBattle'],'msgData':{'roleDataList':[],'monsterDataList':[],'cardDataList':[]}},{'time':1,'msgId':c['commands']['rd_BattleCut'],'msgData':{'frameList':[{'time':1.1,'eventId':c['renderEvents']['BattleBegin'],'data':[]}]}}]}}\nprint(json.dumps(build_replay_index(a,c),separators=(',',':')))\n`;
  const run=spawnSync('python',['-c',code],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const result=JSON.parse(run.stdout);
  assert.deepEqual(result.events[0].data,[]);assert.equal(result.events[0].eventName,'BattleBegin');assert.equal(result.snapshotBoundaryStatus,'COMPLETE');
});

test('decoded replay index treats an omitted live block property as zero and rejects a malformed present value',()=>{
  const code=`import json\nfrom tools.replay_index import build_replay_index\nc=json.load(open('research/evidence/replay-protocol.json',encoding='utf-8'))\na={'schemaVersion':1,'kind':'MORIMENS_DECODED_REPLAY','inputSha256':'abc','decoded':{'battleDat':{},'unZippedRecord':[{'time':0,'msgId':c['commands']['rd_InitBattle'],'msgData':{'roleDataList':[],'monsterDataList':[{'uid':2,'properties':{'hp':100}},{'uid':4,'properties':{'hp':100,'block':'bad'}}],'cardDataList':[{'uid':3}]}},{'time':1,'msgId':c['commands']['rd_BattleCut'],'msgData':{'frameList':[{'time':1.0,'eventId':c['renderEvents']['UseCard'],'data':{'cardUid':3,'camp':1}},{'time':1.1,'eventId':c['renderEvents']['BeHit'],'data':{'roleUid':2,'beHitConfig':{'oldHp':100,'blockLose':0,'castDamage':10}}},{'time':1.2,'eventId':c['renderEvents']['BeHit'],'data':{'roleUid':4,'beHitConfig':{'oldHp':100,'blockLose':0,'castDamage':10}}}]}}]}}\nprint(json.dumps(build_replay_index(a,c),separators=(',',':')))\n`;
  const run=spawnSync('python',['-c',code],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const result=JSON.parse(run.stdout);
  assert.equal(result.hitSnapshots[0].boundaryStatus,'COMPLETE');assert.equal(result.hitSnapshots[0].roles['2'].properties.block,0);
  assert.equal(result.hitSnapshots[1].boundaryStatus,'INCOMPLETE');assert.equal(result.hitSnapshots[1].boundaryIssues[0].code,'MISSING_HIT_PRESTATE');
});

test('decoded replay index resolves property changes serialized before AddNewCard',()=>{
  const code=`import json\nfrom tools.replay_index import build_replay_index\nc=json.load(open('research/evidence/replay-protocol.json',encoding='utf-8'))\na={'schemaVersion':1,'kind':'MORIMENS_DECODED_REPLAY','inputSha256':'abc','decoded':{'battleDat':{},'unZippedRecord':[{'time':0,'msgId':c['commands']['rd_InitBattle'],'msgData':{'roleDataList':[],'monsterDataList':[],'cardDataList':[]}},{'time':1,'msgId':c['commands']['rd_BattleCut'],'msgData':{'frameList':[{'time':1.0,'eventId':c['renderEvents']['PropertyChanged'],'data':{'uid':7,'propertyType':'card_origin_cost','value':2}},{'time':1.1,'eventId':c['renderEvents']['AddNewCard'],'data':{'cards':[{'uid':7,'properties':{}}]}},{'time':1.2,'eventId':c['renderEvents']['UseCard'],'data':{'cardUid':7,'camp':1}}]}}]}}\nprint(json.dumps(build_replay_index(a,c),separators=(',',':')))\n`;
  const run=spawnSync('python',['-c',code],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const result=JSON.parse(run.stdout);
  assert.equal(result.actionSnapshots[0].cards['7'].properties.card_origin_cost,2);assert.equal(result.actionSnapshots[0].boundaryStatus,'COMPLETE');assert.equal(result.snapshotBoundaryStatus,'COMPLETE');
});

test('decoded replay index normalizes an empty Lua property map encoded as a list',()=>{
  const code=`import json\nfrom tools.replay_index import build_replay_index\nc=json.load(open('research/evidence/replay-protocol.json',encoding='utf-8'))\na={'schemaVersion':1,'kind':'MORIMENS_DECODED_REPLAY','inputSha256':'abc','decoded':{'battleDat':{},'unZippedRecord':[{'time':0,'msgId':c['commands']['rd_InitBattle'],'msgData':{'roleDataList':[],'monsterDataList':[],'cardDataList':[{'uid':7,'properties':[]}]}},{'time':1,'msgId':c['commands']['rd_BattleCut'],'msgData':{'frameList':[{'time':1.0,'eventId':c['renderEvents']['PropertyChanged'],'data':{'uid':7,'propertyType':'reserve','value':1}},{'time':1.1,'eventId':c['renderEvents']['UseCard'],'data':{'cardUid':7,'camp':1}}]}}]}}\nprint(json.dumps(build_replay_index(a,c),separators=(',',':')))\n`;
  const run=spawnSync('python',['-c',code],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const result=JSON.parse(run.stdout);
  assert.equal(result.actionSnapshots[0].cards['7'].properties.reserve,1);assert.equal(result.snapshotBoundaryStatus,'COMPLETE');
});

test('decoded replay index normalizes an empty property map after ChangeCardId',()=>{
  const code=`import json\nfrom tools.replay_index import build_replay_index\nc=json.load(open('research/evidence/replay-protocol.json',encoding='utf-8'))\na={'schemaVersion':1,'kind':'MORIMENS_DECODED_REPLAY','inputSha256':'abc','decoded':{'battleDat':{},'unZippedRecord':[{'time':0,'msgId':c['commands']['rd_InitBattle'],'msgData':{'roleDataList':[],'monsterDataList':[],'cardDataList':[{'uid':7,'properties':{}}]}},{'time':1,'msgId':c['commands']['rd_BattleCut'],'msgData':{'frameList':[{'time':1.0,'eventId':c['renderEvents']['ChangeCardId'],'data':{'cardUid':7,'tid':12,'properties':[]}},{'time':1.1,'eventId':c['renderEvents']['PropertyChanged'],'data':{'uid':7,'propertyType':'reserve','value':1}},{'time':1.2,'eventId':c['renderEvents']['UseCard'],'data':{'cardUid':7,'camp':1}}]}}]}}\nprint(json.dumps(build_replay_index(a,c),separators=(',',':')))\n`;
  const run=spawnSync('python',['-c',code],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const result=JSON.parse(run.stdout);
  assert.deepEqual(result.actionSnapshots[0].cards['7'].properties,{reserve:1});
  assert.equal(result.snapshotBoundaryStatus,'COMPLETE');
});
