from pathlib import Path
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'output/pdf/morimens-damage-stacking-mouchette.pdf'
OUT.parent.mkdir(parents=True,exist_ok=True)
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='TitleX',fontName='Helvetica-Bold',fontSize=29,leading=33,textColor=colors.HexColor('#142D43'),spaceAfter=19))
styles.add(ParagraphStyle(name='SubX',fontName='Helvetica-Bold',fontSize=15,leading=19,textColor=colors.HexColor('#087F8C'),spaceBefore=15,spaceAfter=8))
styles.add(ParagraphStyle(name='BodyX',fontName='Helvetica',fontSize=10.5,leading=15,spaceAfter=10,textColor=colors.HexColor('#243746')))
styles.add(ParagraphStyle(name='SmallX',fontName='Helvetica',fontSize=8.5,leading=12,spaceAfter=7,textColor=colors.HexColor('#45596B')))
styles.add(ParagraphStyle(name='BoxX',fontName='Helvetica-Bold',fontSize=11,leading=16,textColor=colors.HexColor('#142D43'),spaceAfter=0))
story=[]
def p(t):story.append(Paragraph(t,styles['BodyX']))
def h(t):story.append(Paragraph(t,styles['SubX']))
def title(n,t,sub):
 story.append(Paragraph('FIELD GUIDE  /  '+n,styles['SmallX']));story.append(Paragraph(t,styles['TitleX']));p(sub)
def box(t):
 tab=Table([[Paragraph(t,styles['BoxX'])]],colWidths=[490]);tab.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),colors.HexColor('#EAF4F4')),('BOX',(0,0),(-1,-1),.5,colors.HexColor('#BDDADA')),('LEFTPADDING',(0,0),(-1,-1),13),('RIGHTPADDING',(0,0),(-1,-1),13),('TOPPADDING',(0,0),(-1,-1),11),('BOTTOMPADDING',(0,0),(-1,-1),11)]));story.append(tab);story.append(Spacer(1,12))
def table(rows,widths):
 data=[[Paragraph(str(c),styles['SmallX']) for c in row] for row in rows]
 t=Table(data,colWidths=widths,hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#EAF4F4')),('VALIGN',(0,0),(-1,-1),'TOP'),('LINEBELOW',(0,0),(-1,-1),.4,colors.HexColor('#D4DFE6')),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),6)]));story.append(t);story.append(Spacer(1,10))
def page():story.append(PageBreak())
title('01','How damage stacks','Morimens research guide - with a focused explanation of Mouchette (the character you called Moucette). Prepared 19 September 2026.')
box('The important distinction: bonuses within one property add. Different multiplier slots multiply. Flat bonuses and extra hits are separate again.')
h('Read the evidence correctly')
p('<b>Runtime-tested arithmetic:</b> 5,411 synthetic cases match copied original PC bytecode exactly across offensive, crit/target and Passive paths. This tests specific arithmetic, not a complete battle.')
p('<b>Recovered mechanics:</b> character skills, state properties and command order are traced from client code and configuration. Their full gameplay execution is still being checked.')
p('<b>Observed gameplay:</b> Frenzy replay screenshots establish some real buffs and damage statistics. No complete hit has yet been predicted from a fully reconstructed state; there are no completed gameplay holdouts.')
h('Scope of this edition')
p('PC downloaded resources 144 / content build 51. Android resources and other regions are not assumed equivalent. Skill names below are descriptive English translations where an official localized name has not been checked. The client identifies Mouchette as character 94450, the character referred to as Moxia in earlier notes.')
h('Inside')
table([['Page','Topic'],['2','The damage pipeline and stacking examples'],['3','Mouchette: flat Strike bonus, hit count and follow-ups'],['4','Mouchette: awakening stacks, crit and sequencing'],['5','Frenzy boss mechanics, other damage types and evidence notes']],[45,445])
p('This is a shareable explanation of current findings, not a claim that the final calculator or every interaction is verified. No private screenshots, account details or extracted game assets are included.')
page()
title('02','The stacking pipeline','A simplified map for an eligible Active hit. The exact implementation preserves more slots and rounding boundaries than this overview shows.')
box('Raw event value x base factors\n<br/>+ resolved STR and eligible flat bonuses\n<br/>x offensive factors -> round -> reductions\n<br/>x crit and target factors + target flat bonus -> round\n<br/>then shields, caps, immunity and HP handling')
h('One bucket versus two buckets')
p('Illustration: +20% and +30% assigned to the <b>same property</b> produce 1 + 0.20 + 0.30 = <b>1.50x</b>. If they belong to <b>different independent slots</b>, they produce 1.20 x 1.30 = <b>1.56x</b>. Matching tooltip words do not prove matching slots.')
p('The Active utility has nine separate internal inside-damage slots. A specific pair of card bonuses shares one additive factor. Other card, character, team and dimension factors may be separate. Source-to-property mapping is essential before combining equipment bonuses.')
h('Why flat bonuses behave differently')
p('Base-stage factors multiply the raw event value before STR and the other flat additions enter. Later offensive and target factors can multiply that combined subtotal. Thus a base-only +20% bonus is not automatically +20% to the whole hit when much of the hit comes from flat Strike damage or STR.')
p('Positive STR gets its effectiveness modifier before joining the subtotal. The recovered preparation sums the character/card/ultimate STR-effectiveness percentages, then applies a separate power-scaling factor. Negative STR does not take the same positive-only scaling branch.')
h('Target effects and crit')
p('Ordinary Vulnerable contributes a separate <b>1.50x</b> factor. More duration layers do not mean repeated 50% multipliers. Psychic Trauma contributes <b>3 percentage points per stack</b> to target slot 2; it adds with other contributions to that slot, then multiplies Vulnerable.')
p('Illustration with other factors neutral: 10 Trauma stacks and Vulnerable give 1.30 x 1.50 = <b>1.95x</b>. A 100-point pre-target hit becomes 195 before other effects. This is an arithmetic example, not a measured hit.')
p('On an eligible critical hit, crit-damage contributions are summed and scaled, then become a multiplier of 1 + bonus/100. A +50% crit-damage bonus means 1.50x on that critical hit; it is separate from the chance to crit.')
page()
title('03','Mouchette: where the damage comes from','Her kit combines several mechanisms. Treating all of them as one generic damage bonus hides the most important interactions.')
h('1 / Ultimate: a team-wide flat Strike addition')
p('The recovered ultimate applies a temporary player state contributing <b>strikecard_damage_plus</b>. It adds a flat amount to eligible Strikes, including other Awakeners\' Strikes. It is not a percentage bonus. Its parameter uses Mouchette\'s BattleAtkForce, a skill-level coefficient and a separate relic-related state factor.')
p('In the selected Frenzy replay, the status panel explicitly showed <b>+653 Strike damage</b>. That number belongs to that recorded build and moment; it is not her universal bonus. The ultimate damage command precedes application of the new buff, so do not retroactively add that newly granted buff to the preceding ultimate hit.')
h('2 / Extra hits multiply opportunities, not just the tooltip')
p('The potency-3 branch applies a marker that adds one to several hit-count expressions. The ordinary Strike uses 1 + marker; Storm Impact uses 5 + marker; Human Explosion uses 2 + marker. The associated buff expires through turn-end handling. Other hit-count modifiers and event processing remain relevant.')
box('Illustration only: if a resolved per-hit amount stays at 1,000, three hits total 3,000. But if STR, target state or a passive changes between hits, calculate each hit separately.')
h('3 / Dramatic Encounter: the Strike-pair follow-up')
p('A listener watches eligible Strike-card uses. Its interval marker alternates, scheduling Dramatic Encounter on the second eligible use. The recovered ordinary trigger cap is <b>4 per turn</b>; a separate enhancement marker can raise it. Count card uses, not individual damage hits.')
p('Dramatic Encounter is an attached action tagged as Strike. Its raw per-hit argument is <b>30% of BattleAtkForce</b>. Its hit count is 1 + 2 x awakening marker + extra-hit marker: normally one, three after awakening, and four when both markers are present. These are recovered expressions, not an end-to-end damage prediction.')
p('The listener, interval markers and follow-up counter have separate roles. Do not assume a five-hit card consumes five follow-up triggers, or assume every attached action recursively counts as a newly played card.')
page()
title('04','Mouchette: stacking','The strongest-looking number in her description is not the only reason her turn can grow so quickly.')
h('Awakening adds a repeated +25% contribution')
p('After awakening is active, each Dramatic Encounter command adds one layer of state 123168 <b>after its damage effect</b>. That state contributes 25 points per changed layer to <b>i_damage_per_strikecard</b>, and clears at turn end. The newly awarded layer therefore should not be assumed to boost the earlier hit in that same command.')
table([['Completed qualifying follow-ups','Contribution to this Strike property','Factor if otherwise neutral'],['1','+25%','1.25x'],['2','+50%','1.50x'],['3','+75%','1.75x'],['4','+100%','2.00x']],[180,180,130])
p('These layers accumulate in the same property. Four layers are <b>not 1.25 to the fourth power</b> (about 2.44x). Other bonuses in the same property add to its total; independent slots may still multiply it. This table isolates one property and does not predict her complete hit.')
h('Death resistance can feed crit')
p('At the recovered potency-1 branch, a stage-state effect takes <b>15% of her death_resist property</b> and applies it through states contributing to crit chance and crit damage. A post-death-resistance event adds a crit-damage state using that expression. Property/state rounding, existing layers and event eligibility must be checked before turning this into a build calculator.')

h('A useful sequencing explanation')
p('Awakening enables the longer follow-up and its stacking Strike modifier. The ultimate supplies the team flat Strike bonus and, in the applicable potency branch, the extra-hit marker. Eligible Strike uses then advance the follow-up pair counter. As follow-ups finish, the temporary Strike property grows for later effects. The exact best order depends on cards, energy, targets and current states; this is a dependency explanation, not a tested optimal rotation.')
h('Copied cards keep their identity')
p('Human Explosion can generate a temporary copy of a prior eligible Strike in its potency-2 branch. A copy normally retains the original skill identity and resolves to that skill\'s Awakener, unless a special-owner override applies. Mouchette generating an Arachne card does not automatically make it use Mouchette\'s ATK. Statistics use command caster and skill ID; animations alone are insufficient evidence.')
page()
title('05','Boss rules and practical checks','High-difficulty encounters can separate the attack number, statistics credit and actual HP change.')
h('Frenzy: Old Embers is an extra event')
p('The traced boss resource reacts to incoming damage. Active and Tentacle events use the full incoming cast amount; Passive and Fixed use half. The trigger selects no more than the remaining resource, consumes stacks, and requests a separate HP change of three times the selected amount. Exclusions, HP-change limits, rounding and callbacks can alter the outcome.')
p('Illustration: an eligible 1,000 Active event with sufficient resource requests a separate 3,000 HP loss and consumes 1,000 stacks. With only 200 stacks left, the extra request is 600. A 1,000 Passive event uses 500 resource and requests 1,500 extra HP loss. These are command-level examples; they do not prove the final HP delta.')
p('Recorded boss turn-one statistics attribute <b>2,205 Strike + 6,615 Old Embers</b> to Arachne. The 3:1 ratio supports the recovered mechanic, but missing event inputs prevent calling it a completed prediction. Mouchette\'s multi-hit and follow-up chains make this separation especially important.')
h('Other mechanics that are easy to mix up')
table([['Mechanic','What the recovered path says'],['DEF','No universal DEF division was found in the traced Active target path. DEF does feed shield-related effects. This does not prove that every mechanic ignores DEF.'],['Passive damage','Three dedicated target multipliers; ceiling, positive-only dimension factor, ceiling, minimum one. No crit in this effect. HP handling comes later.'],['Fixed / Pure','Distinct effect paths. Do not automatically apply Active STR, crit, Vulnerable or Trauma to them. Upstream parameters may already contain scaling.'],['Arachne Fate Cut','Accumulates a state before a guarded Passive hit. Recovered trigger uses layers strictly greater than HP, while its description says at least HP. Boundary is not gameplay verified.'],['Rounding','Active offensive calculation uses epsilon-adjusted ceiling, then reduction-stage floor. Target calculation uses its own ceiling. Do not round every intermediate number indiscriminately.']],[100,390])
h('Evidence and reproduction notes')
story.append(Paragraph('Primary sources: local PC144 configuration entries AwakerConfig 94450; Skill 122483-122488 and 123159; Cmd 122491, 122494, 122499, 123160, 123163; State 123168, 123172, 122502, 124034, 124037. General formulas: BattleUtilServer.ShowDamageFormula, BattleCmdServer.__GetFinalDamage, BEPassiveDamage and BattleEffectServer.CalFinalVal. Supporting research: DAMAGE_FORMULA.md, MODIFIER_BUCKETS.md, CARD_ATTRIBUTION.md, HIGH_DIFFICULTY.md and FATE_CUT.md. Synthetic test counts: 2,262 + 2,097 + 1,052 = 5,411. Gameplay status: two incomplete records; zero completed holdouts. No community build advice is used as proof of a formula.',styles['SmallX']))
def footer(c,d):
 c.setStrokeColor(colors.HexColor('#BDDADA'));c.line(52,43,542,43)
 c.setFont('Helvetica',8);c.setFillColor(colors.HexColor('#45596B'));c.drawString(52,29,'MORIMENS / PC144 research edition / gameplay verification pending');c.drawRightString(542,29,str(d.page))
doc=SimpleDocTemplate(str(OUT),pagesize=(595.28,841.89),rightMargin=52,leftMargin=52,topMargin=46,bottomMargin=58,title='Morimens damage stacking - Mouchette',author='Morimens research project')
doc.build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT)
