import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {runAttachedCardPipeline} from '../engine/attached-card-pipeline.mjs';

const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const readConfig=name=>{const bytes=readFileSync(`research/extracted/config/${name}.json`);return {data:JSON.parse(bytes),sha256:hash(bytes)};};
const skill=readConfig('Skill'),battleApi=readConfig('BattleApi'),command=readConfig('Cmd'),state=readConfig('State');
const source={build:'pc-res144-build51',skills:skill.data,battleApi:battleApi.data,commands:command.data,sourceHashes:{Skill:skill.sha256,BattleApi:battleApi.sha256,Cmd:command.sha256}};
const priorBytes=readFileSync('output/pdf/mouchette-equipped-baseline-calculation.json'),prior=JSON.parse(priorBytes),pursuit=prior.rounds[0].pursuit,{value,...offense}=pursuit.utilityInputs;
const stateIds=[123168,124036,123165,123307,123523,123167];
const definition=id=>({id,maximum:String(state.data[String(id)].MaxLayer),properties:Object.entries(state.data[String(id)].ExistProperty??{}).map(([property,expression])=>({property,expression:String(expression)})),skillLevel:1,casterRoleId:50,specialValue:0,banned:false});
const input={schemaVersion:1,kind:'morimens-attached-card-pipeline',build:'pc-res144-build51',attach:{schemaVersion:1,kind:'morimens-attach-post-action',build:'pc-res144-build51',parameters:[123159,1,0,1],casterUid:77,targetUid:50,casterSealAttachPost:0,targetPresent:true,targetIsMonster:false},cardContext:{cardUid:900,camp:3,targetType:456,hasPre:false,preCmdId:null,progression:{isAwaker:true,breakSkillLevel:0,potencyLevel:0,variables:{BattleAtkForce:prior.attackM},conditionResults:{},stateQueries:{'CmdCaster.GetStateLayer':{'122512':1,'124039':0}}}},damagePrefix:{targetBinding:{expression:'RandomEnemy',resolution:'supplied-single-target'},variables:{},offense,targetModifiers:pursuit.target,targetState:{hp:1000000,block:0},repeatModifiers:{plus:0,per:0},immune:false,presentationPolicy:'record-only'},stateSuffix:{variables:{},stateQueries:{'CmdCaster.GetStateLayer':{'122512':1},'PlayerRole.GetStateLayer':{'123723':0,'123167':0}},stateQueryTargets:{'CmdCaster.GetStateLayer':'CmdCaster','PlayerRole.GetStateLayer':'PlayerRole'},targetBindings:{CmdCaster:50,PlayerRole:1},roles:[{id:50,roleType:'Awakener',properties:{i_crit_per:0,i_crit_damage_per:0,i_damage_per_strikecard:0},tentacleContext:null},{id:1,roleType:'Player',properties:{i_crit_per:0,i_crit_damage_per:0},tentacleContext:null}],definitions:stateIds.map(definition)}};
const result=runAttachedCardPipeline(input,source),hits=result.damagePrefix.execution.hits.map(row=>row.modeledHpLost),strikeBonusAfter=result.stateSuffix.roles.find(row=>row.id===50).properties.i_damage_per_strikecard;
const exact=JSON.stringify(hits)===JSON.stringify(Array(3).fill(pursuit.preHitDamage))&&result.damagePrefix.modeledHpLost===prior.rounds[0].pursuitTotal&&strikeBonusAfter===25&&result.commandRowsCompleted;
const report={schemaVersion:1,kind:'MORIMENS_MOUCHETTE_ATTACHED_PIPELINE_CROSSCHECK',status:exact?'EXACT_CASE_STUDY_COMPONENT_MATCH':'MISMATCH',build:'pc-res144-build51',sourceHashes:{...source.sourceHashes,State:state.sha256,priorCaseStudy:hash(priorBytes)},inputs:{attack:prior.attackM,rouseState122512:1,extraRepeatState124039:0,teamAmplification:prior.setup.teamDamageAmplificationPercent,criticalDamage:prior.setup.critDamageStat},result:{baseArguments:result.commandResolution.baseArguments,argumentBindings:result.commandResolution.plan.argumentBindings,hits,modeledHpLost:result.damagePrefix.modeledHpLost,priorPerHit:pursuit.preHitDamage,priorPursuitTotal:prior.rounds[0].pursuitTotal,strikeDamagePropertyAfter: strikeBonusAfter,commandRowsCompleted:result.commandRowsCompleted},scope:'Replays the first Mouchette attached pursuit from the earlier equipped case-study vectors through the catalog-driven attached-card pipeline. Confirms three 4,489 hits and that the +25 Strike-card property is applied after them.',limitations:['The prior equipped report is explicitly incomplete for Arachne realm/team reconstruction','Inputs are case-study vectors, not a reconstructed live battle snapshot','Effect scheduling, callbacks, target acquisition, gameplay and holdout validation remain excluded','No publication credit']};
writeFileSync('research/evidence/mouchette-attached-pipeline-crosscheck.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({status:report.status,result:report.result,output:'research/evidence/mouchette-attached-pipeline-crosscheck.json'},null,2));
if(!exact)process.exitCode=1;
